force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <displayFormat>FI-{0000}</displayFormat>
        <label>Forecast Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/BU_Approval__c.field-meta.xml
<CustomField>
    <fullName>BU_Approval__c</fullName>
    <inlineHelpText>Dedicated for Item Type - Opportunity Product</inlineHelpText>
    <label>BU Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Opportunity</label>
    <referenceTo>Forecast_Opportunity__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/Forecast_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Opportunity Product.</description>
    <label>Forecast Opportunity</label>
    <nameField>
        <displayFormat>FO - {0000}</displayFormat>
        <label>Forecast Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Opportunity__c/fields/BU_Approval__c.field-meta.xml
<CustomField>
    <fullName>BU_Approval__c</fullName>
    <label>BU Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Forecast Opportunities</relationshipLabel>
    <relationshipName>Forecast_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ForecastOpportunityEntryWrapper.cls
public class ForecastOpportunityEntryWrapper{
    @AuraEnabled public Id recordId;
    @AuraEnabled public String name;
    @AuraEnabled public String comment;
    @AuraEnabled public String buApproval;

    @AuraEnabled public Boolean approved = false;
    @AuraEnabled public Boolean rejected = false;
    @AuraEnabled public Boolean pending = false;

    @AuraEnabled public Id opportunityId;
    @AuraEnabled public Map<String, Decimal> forecastNumbers = new Map<String, Decimal>(); 
    
    public ForecastOpportunityEntryWrapper(Forecast_Item__c item, List<String> dateRange){ 
        this.recordId = item.Forecast_Opportunity__c;
        this.name = item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Name;
        this.comment = item.Forecast_Opportunity__r.Comment__c;
        this.buApproval = item.Forecast_Opportunity__r.BU_Approval__c;
        this.opportunityId = item.Forecast_Opportunity__r.Opportunity_Product__r.OpportunityId;

        for (String d : dateRange) {
            this.forecastNumbers.put(d, 0);
        }  

        if(item.Forecast_Opportunity__r.BU_Approval__c == Constants.approval.APPROVED){
            this.approved = true;
        }else if(item.Forecast_Opportunity__r.BU_Approval__c == Constants.approval.REJECTED){
            this.rejected = true;
        }else{
            this.pending = true;
        }
    }
}