force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <displayFormat>FI-{0000}</displayFormat>
        <label>Forecast Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/Forecast_Month__c.object-meta.xml
<CustomObject>
    <label>Forecast Month</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Forecast Moth</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Months</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Month__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Forecast_Product__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Forecast_Product__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Product__c</fullName>
    <label>Forecast Product</label>
    <referenceTo>Forecast_Product__c</referenceTo>
    <relationshipLabel>Forecast Months</relationshipLabel>
    <relationshipName>Forecast_Months</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Forecast_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/Forecast_Product__c.object-meta.xml
<CustomObject>
    <label>Forecast Product</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forecast Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Direct_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Direct_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EMEA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>EMEA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for EMEA region.</inlineHelpText>
    <label>EMEA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>NACA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for NACA region.</inlineHelpText>
    <label>NACA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ForecastMonthTriggerHelper.cls
public with sharing class ForecastMonthTriggerHelper {
	private Map<Id, Forecast_Month__c> newRecordsMap;
	private List<Forecast_Month__c> newRecordsList;

	public ForecastMonthTriggerHelper(List<SObject> newRecordsList, Map<Id, SObject> newRecordsMap) {
		this.newRecordsList = (List<Forecast_Month__c>) newRecordsList;
		this.newRecordsMap = (Map<Id, Forecast_Month__c>) newRecordsMap;
	}

	public ForecastMonthTriggerHelper(List<SObject> newRecordsList) {
		this.newRecordsList = (List<Forecast_Month__c>) newRecordsList;
	}

	public ForecastMonthTriggerHelper setExternalIds() {
		Set<Id> forecastProductsIds = new Set<Id>();
		for(Forecast_Month__c forecastMonth : newRecordsList) {
			forecastProductsIds.add(forecastMonth.Forecast_Product__c);
		}
		if(forecastProductsIds.isEmpty()) {
			return this;
		}

		Map<Id,Forecast_Product__c> forecastProducts = fetchForecastProductsByIds(forecastProductsIds);
		for(Forecast_Month__c forecastMonth : newRecordsList) {
			Forecast_Product__c forecastProduct = forecastProducts.get(forecastMonth.Forecast_Product__c);
			forecastMonth.External_ID__c = forecastProduct.Account__c + '-' + forecastProduct.Product__c + '-'
					+  ForecastUtil.getMonthUniqueId(forecastMonth.Month__c) + '-'+ (forecastProduct.Direct_Enabled__c ? '0' : '1');
            system.debug(forecastMonth.External_ID__c);
		}
		return this;
	}

	private Map<Id,Forecast_Product__c> fetchForecastProductsByIds(Set<Id> forecastProductsIds) {
		return new Map<Id, Forecast_Product__c> ([
			SELECT Id, Account__c, Product__c,Direct_Enabled__c
			FROM Forecast_Product__c
			WHERE Id IN :forecastProductsIds
		]);
	}

	private List<OrderItem> fetchOrderItemsByParameters(Set<Id> accountsIds, Set<Id> productsIds, Set<Integer> months, Set<Integer> years) {
		return [
				SELECT Id, Shipment_Date__c, Order.AccountId, Product2Id, Quantity, Order.RecordType.DeveloperName,
						Product2.EMEA_Case_Qty__c, Product2.NACA_Case_Qty__c
				FROM OrderItem
				WHERE Order.AccountId IN :accountsIds
				AND Product2Id IN :productsIds
				AND CALENDAR_MONTH(Shipment_Date__c) IN :months
				AND CALENDAR_YEAR(Shipment_Date__c) IN :years
		];
	}

	public ForecastMonthTriggerHelper createForecastItems() {
		Set<Id> forecastProductsIds = new Set<Id>();
		Set<Integer> months = new Set<Integer>();
		Set<Integer> years = new Set<Integer>();
		for(Forecast_Month__c forecastMonth : newRecordsList) {
			forecastProductsIds.add(forecastMonth.Forecast_Product__c);
			months.add(forecastMonth.Month__c.month());
			years.add(forecastMonth.Month__c.year());
			years.add(forecastMonth.Month__c.year()-1);
		}
		if(forecastProductsIds.isEmpty()) {
			return this;
		}

		Map<Id,Forecast_Product__c> forecastProducts = fetchForecastProductsByIds(forecastProductsIds);
		Set<Id> accountsIds = new Set<Id>();
		Set<Id> productsIds = new Set<Id>();
		for(Forecast_Product__c forecastProduct : forecastProducts.values()) {
			accountsIds.add(forecastProduct.Account__c);
			productsIds.add(forecastProduct.Product__c);
		}

		List<OrderItem> orderProducts = fetchOrderItemsByParameters(accountsIds, productsIds, months, years);
		List<Forecast_Item__c> forecastItemsToInsert = ForecastItemHelper.buildNewForecastItems(newRecordsList, forecastProducts, orderProducts);
		system.debug('forecastItemsToInsert-->'+forecastItemsToInsert);
		insert forecastItemsToInsert;
		return this;
	}
}