force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <displayFormat>FI-{0000}</displayFormat>
        <label>Forecast Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast Month</label>
    <referenceTo>Forecast_Month__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Opportunity</label>
    <referenceTo>Forecast_Opportunity__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Product</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Current Order</fullName>
            </value>
            <value>
                <fullName>Previous Year Order</fullName>
            </value>
            <value>
                <fullName>Base</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Order_Product__c.field-meta.xml
<CustomField>
    <fullName>Order_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/Forecast_Month__c.object-meta.xml
<CustomObject>
    <label>Forecast Month</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Forecast Moth</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Months</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Month__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Forecast_Product__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Forecast_Product__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Product__c</fullName>
    <label>Forecast Product</label>
    <referenceTo>Forecast_Product__c</referenceTo>
    <relationshipLabel>Forecast Months</relationshipLabel>
    <relationshipName>Forecast_Months</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Forecast_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/Forecast_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Opportunity Product.</description>
    <label>Forecast Opportunity</label>
    <nameField>
        <displayFormat>FO - {0000}</displayFormat>
        <label>Forecast Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Forecast Opportunities</relationshipLabel>
    <relationshipName>Forecast_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/Forecast_Product__c.object-meta.xml
<CustomObject>
    <label>Forecast Product</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forecast Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shipment_Date__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Date__c</fullName>
    <label>Shipment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EMEA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>EMEA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for EMEA region.</inlineHelpText>
    <label>EMEA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>NACA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for NACA region.</inlineHelpText>
    <label>NACA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ForecastItemHelper.cls
public with sharing class ForecastItemHelper {
	public static Boolean isOrderItemDateConnectedToForecastItem(OrderItem orderItem, Forecast_Item__c forecastItem) {
		return forecastItem.Forecast__r.Month__c.month() == orderItem.Shipment_Date__c.month()
				&& (forecastItem.Forecast__r.Month__c.year() == orderItem.Shipment_Date__c.year()
				|| forecastItem.Forecast__r.Month__c.year()-1 == orderItem.Shipment_Date__c.year());
	}

	@TestVisible
	private static Boolean isOrderProductConnectedToForecastMonth(OrderItem orderProduct, Forecast_Month__c forecastMonth, Forecast_Product__c forecastProduct) {
		return orderProduct.Order.AccountId == forecastProduct.Account__c
				&& orderProduct.Product2Id == forecastProduct.Product__c
				&& orderProduct.Shipment_Date__c.month() == forecastMonth.Month__c.month()
				&& (
				orderProduct.Shipment_Date__c.year() == forecastMonth.Month__c.year()
						|| orderProduct.Shipment_Date__c.year() == forecastMonth.Month__c.year()-1
		);
	}

	public static Forecast_Item__c buildForecastItem(OrderItem orderProduct, Date forecastMonthDate, Forecast_Item__c forecastItem) {
		forecastItem.Order_Product__c = orderProduct.Id;

		if(orderProduct.Order.RecordType.DeveloperName == Constants.order.RECORD_TYPE_NACA) {
			forecastItem.Quantity__c = orderProduct.Product2.NACA_Case_Qty__c * orderProduct.Quantity;
		} else if(orderProduct.Order.RecordType.DeveloperName == Constants.order.RECORD_TYPE_EMEA) {
			forecastItem.Quantity__c = orderProduct.Product2.EMEA_Case_Qty__c * orderProduct.Quantity;
		}

		if(orderProduct.Shipment_Date__c.year() == forecastMonthDate.year()) {
			forecastItem.Item_Type__c = Constants.forecastItem.ITEM_TYPE_CURRENT_ORDER;
		} else if(orderProduct.Shipment_Date__c.year() == forecastMonthDate.year()-1) {
			forecastItem.Item_Type__c = Constants.forecastItem.ITEM_TYPE_PREVIOUS_YEAR_ORDER;
		}
		return forecastItem;
	}

	public static List<Forecast_Item__c> buildNewForecastItems(List<Forecast_Month__c> forecastMonths, Map<Id,Forecast_Product__c> forecastProductsByIds, List<OrderItem> orderProducts) {
		List<Forecast_Item__c> forecastItemsToInsert = new List<Forecast_Item__c>();

		for(Forecast_Month__c forecastMonth : forecastMonths) {
			Forecast_Product__c forecastProduct = forecastProductsByIds.get(forecastMonth.Forecast_Product__c);

			for(OrderItem orderProduct : orderProducts) {
				if(isOrderProductConnectedToForecastMonth(orderProduct, forecastMonth, forecastProduct)) {
					Forecast_Item__c forecastItem = buildForecastItem(
							orderProduct,
							forecastMonth.Month__c,
							new Forecast_Item__c(
									Forecast__c = forecastMonth.Id,
									CurrencyIsoCode = forecastMonth.CurrencyIsoCode
							));

					forecastItemsToInsert.add(forecastItem);
				}
			}
		}
		return forecastItemsToInsert;
	}

	public void deactivateOpportunityItems(Set<Id> oppLineItemIds){
		List<Forecast_Opportunity__c> forecastOppsForUpdate = new List<Forecast_Opportunity__c>();
		List<Forecast_Item__c> forecastItemsForUpdate = new List<Forecast_Item__c>();

		for(Forecast_Opportunity__c opp: getOppRelatedForecastRecords(oppLineItemIds)){
			opp.Comment__c = 'Opportunity Product ' + opp.Opportunity_Product__r.Name + ' has been deleted';
			forecastOppsForUpdate.add(opp);

			for(Forecast_Item__c item: opp.Forecast_Items__r){
				item.Active__c = false;
				forecastItemsForUpdate.add(item);
			}
		}
		update forecastOppsForUpdate;
		update forecastItemsForUpdate;
	}

	private List<Forecast_Opportunity__c> getOppRelatedForecastRecords(Set<Id> oppLineItemIds){
		return [
			SELECT Id, Opportunity_Product__c, Opportunity_Product__r.Name,
			(SELECT Id FROM Forecast_Items__r WHERE Forecast__r.Month__c >= :Date.today().toStartOfMonth())
			FROM Forecast_Opportunity__c 
			WHERE Opportunity_Product__c IN :oppLineItemIds
		];
	}
}