force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <displayFormat>FI-{0000}</displayFormat>
        <label>Forecast Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast Month</label>
    <referenceTo>Forecast_Month__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Opportunity</label>
    <referenceTo>Forecast_Opportunity__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <label>Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/Forecast_Month__c.object-meta.xml
<CustomObject>
    <label>Forecast Month</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Forecast Moth</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Months</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Month__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Forecast_Product__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Forecast_Product__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Product__c</fullName>
    <label>Forecast Product</label>
    <referenceTo>Forecast_Product__c</referenceTo>
    <relationshipLabel>Forecast Months</relationshipLabel>
    <relationshipName>Forecast_Months</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Forecast_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/Forecast_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Opportunity Product.</description>
    <label>Forecast Opportunity</label>
    <nameField>
        <displayFormat>FO - {0000}</displayFormat>
        <label>Forecast Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <label>Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Forecast Opportunities</relationshipLabel>
    <relationshipName>Forecast_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/Forecast_Product__c.object-meta.xml
<CustomObject>
    <label>Forecast Product</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forecast Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Direct_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Direct_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Local_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Local_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Local Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD &amp; RUP Syringe</fullName>
            </value>
            <value>
                <fullName>Alcohol Swabs</fullName>
            </value>
            <value>
                <fullName>Allergy Syringe</fullName>
            </value>
            <value>
                <fullName>Anesthesia Needles</fullName>
            </value>
            <value>
                <fullName>Beard Cover</fullName>
            </value>
            <value>
                <fullName>Blood Collection Holders &amp; Accessories</fullName>
            </value>
            <value>
                <fullName>Blood Collection Tube</fullName>
            </value>
            <value>
                <fullName>Blood Pressure Monitors</fullName>
            </value>
            <value>
                <fullName>Blunt Fill Needle &amp; Filter Needle</fullName>
            </value>
            <value>
                <fullName>Blunt Fill Needle Combo</fullName>
            </value>
            <value>
                <fullName>Bouffant Cap</fullName>
            </value>
            <value>
                <fullName>Catheter Dressing</fullName>
            </value>
            <value>
                <fullName>Coverall</fullName>
            </value>
            <value>
                <fullName>Enteral Syringe</fullName>
            </value>
            <value>
                <fullName>Exam Gloves</fullName>
            </value>
            <value>
                <fullName>Face Sheild</fullName>
            </value>
            <value>
                <fullName>Flush Syringe - Saline</fullName>
            </value>
            <value>
                <fullName>Gowns</fullName>
            </value>
            <value>
                <fullName>Heel Blood Lancets</fullName>
            </value>
            <value>
                <fullName>HFNC</fullName>
            </value>
            <value>
                <fullName>Hood</fullName>
            </value>
            <value>
                <fullName>Infusion Accessories</fullName>
            </value>
            <value>
                <fullName>IV Accessories</fullName>
            </value>
            <value>
                <fullName>IV Lines</fullName>
            </value>
            <value>
                <fullName>Lab Coat</fullName>
            </value>
            <value>
                <fullName>Mask</fullName>
            </value>
            <value>
                <fullName>Medical Supplies - Other</fullName>
            </value>
            <value>
                <fullName>Non-Invasive Ventilator</fullName>
            </value>
            <value>
                <fullName>Oral Dispensing</fullName>
            </value>
            <value>
                <fullName>Oral Syringe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/EMEA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>EMEA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for EMEA region.</inlineHelpText>
    <label>EMEA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>NACA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for NACA region.</inlineHelpText>
    <label>NACA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <displayFormat>PRO-LINE-{0000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Fulfillment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Shipment</fullName>
    </customValue>
    <customValue>
        <fullName>Local Warehouse</fullName>
    </customValue>
    <masterLabel>Fulfillment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD &amp; RUP Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>AD &amp; RUP Syringe with Safety Arm</fullName>
    </customValue>
    <customValue>
        <fullName>Alcohol Swabs</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use Cassettes</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use IV Sets</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia needles</fullName>
    </customValue>
    <customValue>
        <fullName>Beard Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Collection Holders &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Collection Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Blunt Fill Needle &amp; Filter Needle</fullName>
    </customValue>
    <customValue>
        <fullName>Blunt Fill Needle Combo</fullName>
    </customValue>
    <customValue>
        <fullName>Bouffant Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Catheter dressing</fullName>
    </customValue>
    <customValue>
        <fullName>CGM System-Split Type</fullName>
    </customValue>
    <customValue>
        <fullName>Coverall</fullName>
    </customValue>
    <customValue>
        <fullName>Covid Test</fullName>
    </customValue>
    <customValue>
        <fullName>Devices for capillary blood collection</fullName>
    </customValue>
    <customValue>
        <fullName>Enteral Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pump Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pump Cassette</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Gloves</fullName>
    </customValue>
    <customValue>
        <fullName>Face shield</fullName>
    </customValue>
    <customValue>
        <fullName>Flush Syringe - Saline</fullName>
    </customValue>
    <customValue>
        <fullName>Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Heel Blood Lancets</fullName>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunitySetForecastDAO.cls
public with sharing class OpportunitySetForecastDAO {
	public static Opportunity fetchOpportunityById(Id opportunityId) {
		return [
				SELECT Id, AccountId, RecordTypeId, RecordType.DeveloperName, CloseDate, StageName,
				(SELECT Id, CurrencyIsoCode, HasSchedule, ListPrice, Product2Id, Product2.Name, Product2.NACA_Case_Qty__c,
						Product2.EMEA_Case_Qty__c, Product2.ProductCode, Product2.Product_Line__c, Quantity
				FROM OpportunityLineItems)
				FROM Opportunity
				WHERE Id =: opportunityId
		];
	}

	public static List<OpportunityLineItem> fetchOpportunityLineItemsByIds(Set<Id> oppLineItemsIds) {
		return [
				SELECT Id, CurrencyIsoCode, HasSchedule, ListPrice, Product2Id, Product2.Name, Product2.NACA_Case_Qty__c,
						Product2.EMEA_Case_Qty__c, Quantity, Opportunity.CloseDate
				FROM OpportunityLineItem
				WHERE Id IN :oppLineItemsIds
		];
	}

	public static List<Forecast_Item__c> fetchForecastItemsByForecastOpportunityIdsAndDateRange(Set<Id> forecastOppsIds, Date startDate, Date endDate) {
		return [
				SELECT Id, External_ID__c
				FROM Forecast_Item__c
				WHERE Forecast__r.Month__c >= :startDate
				AND Forecast__r.Month__c <= :endDate
				AND Forecast_Opportunity__c IN :forecastOppsIds
		];
	}

	public static List<Forecast_Month__c> fetchForecastMonthsByForecastProductIdAndDateRange(Set<Id> forecastProductIds, Date startDate, Date endDate) {
		return [
				SELECT Id, Forecast_Product__c, Month__c, External_ID__c
				FROM Forecast_Month__c
				WHERE Month__c >= :startDate
				AND Month__c <= :endDate
				AND Forecast_Product__c IN :forecastProductIds
		];
	}

	public static List<Forecast_Opportunity__c> fetchForecastOpportunitiesByOppLineItemIds(Set<Id> oppLineItemIds) {
		return [
				SELECT Id, Opportunity_Product__c, Opportunity_Product__r.Product2Id, Comment__c, External_Id__c, Fulfillment__c
				FROM Forecast_Opportunity__c
				WHERE Opportunity_Product__c IN :oppLineItemIds
		];
	}

	public static List<Forecast_Product__c> fetchForecastProductsByProductsAndAccountIds(Set<Id> productsIds, Id accountId) {
		return [
				SELECT Id, Account__c, Product__c, Local_Enabled__c, Direct_Enabled__c
				FROM Forecast_Product__c
				WHERE Account__c = :accountId
				AND Product__c IN :productsIds
				AND (Local_Enabled__c = TRUE OR Direct_Enabled__c = TRUE)
		];
	}

	public static List<OpportunityLineItemSchedule> fetchOppLineItemSchedules(Set<Id> oppLineItemsIds, Date startDate, Date endDate) {
		return [
				SELECT Id, ScheduleDate, Quantity, OpportunityLineItemId
				FROM OpportunityLineItemSchedule
				WHERE ScheduleDate >= :startDate
				AND ScheduleDate <= :endDate
				AND OpportunityLineItemId IN :oppLineItemsIds
		];
	}
}