force-app/main/default/objects/Checklist_Action__c/Checklist_Action__c.object-meta.xml
<CustomObject>
    <label>Checklist Action</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Checklist Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Action__c/fields/Action_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Action_Timestamp__c</fullName>
    <label>Action Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Checklist_Action__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Checklist Actions</relationshipLabel>
    <relationshipName>Checklist_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Action__c/fields/Checklist_Item__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Checklist Item</label>
    <referenceTo>Checklist_Items__c</referenceTo>
    <relationshipLabel>Checklist Actions</relationshipLabel>
    <relationshipName>Checklist_Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_Items__c/Checklist_Items__c.object-meta.xml
<CustomObject>
    <label>Checklist Items</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Checklist Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_Items__c/fields/Checklist__c.field-meta.xml
<CustomField>
    <fullName>Checklist__c</fullName>
    <label>Checklist</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Checklist_Items__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Related To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_Items__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Related_To__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChecklistViewerController.cls
public with sharing class ChecklistViewerController {
    @AuraEnabled(cacheable=true)
    public static List<Checklist_Items__c> getChecklistItems(Id recordId, String objectName) {
        String objectLabel = getObjectLabel(objectName);
        return [
            SELECT Id, Checklist__c, IsActive__c, Related_To__c, Status__c
            FROM Checklist_Items__c
            WHERE IsActive__c = true
            AND Related_To__c = :objectLabel
			ORDER BY Order__c ASC
        ];
    }

    private static String getObjectLabel(String objectApiName) {
        Schema.SObjectType objType = Schema.getGlobalDescribe().get(objectApiName);
        return objType != null ? objType.getDescribe().getLabel() : null;
    }

	@AuraEnabled(cacheable=true)
    public static List<Checklist_Action__c> getCompletedChecklistActions(Id relatedRecordId) {
        return [
            SELECT Checklist_Item__c
            FROM Checklist_Action__c
            WHERE Case__c = :relatedRecordId
        ];
    }

	 @AuraEnabled
    public static void createChecklistAction(Id checklistItemId, Id relatedRecordId, String objectType) {
        Checklist_Action__c action = new Checklist_Action__c();
        action.Checklist_Item__c = checklistItemId;
        action.Action_Timestamp__c = DateTime.now();
        
        // Set related record lookup based on object type
         if (objectType == 'Case') {
            action.Case__c = relatedRecordId;
        }
        insert action;
    }
}