force-app/main/default/objects/Forecast_Month__c/Forecast_Month__c.object-meta.xml
<CustomObject>
    <label>Forecast Month</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Forecast Moth</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Months</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Month__c/fields/Adjustments_Total__c.field-meta.xml
<CustomField>
    <fullName>Adjustments_Total__c</fullName>
    <formula>IF( Forecast_Product__r.Direct_Enabled__c , Adjustments_Total_Direct__c, 0) +  IF( Forecast_Product__r.Local_Enabled__c , Adjustments_Total_Warehouse__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjustments Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Base_Total__c.field-meta.xml
<CustomField>
    <fullName>Base_Total__c</fullName>
    <formula>IF( Forecast_Product__r.Direct_Enabled__c , Base_Direct__c, 0) + IF( Forecast_Product__r.Local_Enabled__c , Base_Warehouse__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Current_Orders__c.field-meta.xml
<CustomField>
    <fullName>Current_Orders__c</fullName>
    <label>Current Orders</label>
    <summarizedField>Forecast_Item__c.Quantity__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Item__c.Item_Type__c</field>
        <operation>equals</operation>
        <value>Current Order</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Forecast_Item__c.External_Id__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Item__c.Forecast__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Forecast_Total__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Total__c</fullName>
    <formula>Base_Total__c +  Opportunities_Total__c +  Adjustments_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forecast Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Opportunities_Total__c.field-meta.xml
<CustomField>
    <fullName>Opportunities_Total__c</fullName>
    <formula>IF( Forecast_Product__r.Direct_Enabled__c , Opportunities_Total_Direct__c, 0) + IF( Forecast_Product__r.Local_Enabled__c , Opportunities_Total_Warehouse__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunities Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Previous_Year_Orders__c.field-meta.xml
<CustomField>
    <fullName>Previous_Year_Orders__c</fullName>
    <label>Previous Year Orders</label>
    <summarizedField>Forecast_Item__c.Quantity__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Item__c.Item_Type__c</field>
        <operation>equals</operation>
        <value>Previous Year Order</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Forecast_Item__c.External_Id__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Item__c.Forecast__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ForecastProductTotalsWrapper.cls
public class ForecastProductTotalsWrapper{
    private string volume;
    @AuraEnabled public ForecastProductInfoWrapper productInfo;
    @AuraEnabled public String warehouseNameDirect;
    @AuraEnabled public String warehouseNameLocal;
    @AuraEnabled public Boolean directEnabled;
    @AuraEnabled public Boolean localEnabled;

    @AuraEnabled public Map<String, Decimal> previousYearOrdersMap = new Map<String, Decimal>();
    @AuraEnabled public Map<String, Decimal> currentYearOrdersMap = new Map<String, Decimal>();
    @AuraEnabled public Map<String, Decimal> baseTotalMap = new Map<String, Decimal>();
    @AuraEnabled public Map<String, Decimal> opportunitiesTotalMap = new Map<String, Decimal>();
    @AuraEnabled public Map<String, Decimal> adjustmentsTotalMap = new Map<String, Decimal>();
    @AuraEnabled public Map<String, Decimal> forecastTotalMap = new Map<String, Decimal>();

    public ForecastProductTotalsWrapper(Product2 product, String AccountName, String AccountId, String volume, Boolean directEnabled, Boolean localEnabled, Warehouse__c warehouse,Decimal UnitPrice){
        this.productInfo = new ForecastProductInfoWrapper(product);
        this.productInfo.UnitPrice = UnitPrice;
        this.productInfo.AccountName = AccountName;
        this.productInfo.AccountId = AccountId;
        this.volume = volume; 
        this.directEnabled = directEnabled;
        this.localEnabled = localEnabled;

        if(localEnabled && warehouse != null){
            this.warehouseNameLocal = warehouse.Name;
        }

        if(directEnabled && warehouse != null){
            this.warehouseNameDirect = warehouse.Name;
        }
    }

    public ForecastProductTotalsWrapper setData(List<String> dateRange, List<Forecast_Month__c> forecastMonths){
        for (String d : dateRange) {
            previousYearOrdersMap.put(d, 0);
            currentYearOrdersMap.put(d, 0);
            baseTotalMap.put(d, 0);
            opportunitiesTotalMap.put(d, 0);
            adjustmentsTotalMap.put(d, 0);
            forecastTotalMap.put(d, 0);
        }

        for(Forecast_Month__c forecastMonth: forecastMonths){
            String key = ForecastUtil.getMonthUniqueId(forecastMonth.Month__c);
            
            previousYearOrdersMap.put(key, ForecastUtil.getQuantityInVolume(forecastMonth.Previous_Year_Orders__c, volume, productInfo.uom));
            currentYearOrdersMap.put(key, ForecastUtil.getQuantityInVolume(forecastMonth.Current_Orders__c, volume, productInfo.uom));
            baseTotalMap.put(key, ForecastUtil.getQuantityInVolume(forecastMonth.Base_Total__c, volume, productInfo.uom));
            opportunitiesTotalMap.put(key, ForecastUtil.getQuantityInVolume(forecastMonth.Opportunities_Total__c, volume, productInfo.uom));
            adjustmentsTotalMap.put(key, ForecastUtil.getQuantityInVolume(forecastMonth.Adjustments_Total__c, volume, productInfo.uom));
            forecastTotalMap.put(key, ForecastUtil.getQuantityInVolume(forecastMonth.Forecast_Total__c, volume, productInfo.uom));                
        }
        
        return this;
    }
}