force-app/main/default/objects/Product2/fields/Branding__c.field-meta.xml
<CustomField>
    <fullName>Branding__c</fullName>
    <label>Branding</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Cobrand</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Own Brand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Animal Health</fullName>
            </value>
            <value>
                <fullName>Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Gloves</fullName>
            </value>
            <value>
                <fullName>Hygiene Products</fullName>
            </value>
            <value>
                <fullName>Infusion</fullName>
            </value>
            <value>
                <fullName>Injection</fullName>
            </value>
            <value>
                <fullName>Lab Supplies</fullName>
            </value>
            <value>
                <fullName>Medical Electronic</fullName>
            </value>
            <value>
                <fullName>Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Medical System</fullName>
            </value>
            <value>
                <fullName>Medication Preparation</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Oral, Enteral and Irrigation Administration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pharma System</fullName>
            </value>
            <value>
                <fullName>Protective Apparel</fullName>
            </value>
            <value>
                <fullName>Regional Anesthesia</fullName>
            </value>
            <value>
                <fullName>Respiratory Supplies &amp; Devices</fullName>
            </value>
            <value>
                <fullName>Sample collection</fullName>
            </value>
            <value>
                <fullName>NEW PRODUCT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finished Product</fullName>
            </value>
            <value>
                <fullName>Raw material</fullName>
            </value>
            <value>
                <fullName>Semi-finished Product</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Active__c.field-meta.xml
<CustomField>
    <fullName>NACA_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if Product is available/active for NACA region.</description>
    <inlineHelpText>Determines if Product is available/active for NACA region.</inlineHelpText>
    <label>US Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Box_Quantity__c.field-meta.xml
<CustomField>
    <fullName>NACA_Box_Quantity__c</fullName>
    <inlineHelpText>Box Quantity for NACA region.</inlineHelpText>
    <label>NACA Box Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>NACA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for NACA region.</inlineHelpText>
    <label>NACA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medication Delivery</fullName>
            </value>
            <value>
                <fullName>Home-Care</fullName>
            </value>
            <value>
                <fullName>Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Diagnostic</fullName>
            </value>
            <value>
                <fullName>Dyalisis and Respiratory Care</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Advanced Wound Dressing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alcohol swabs non-sterile</fullName>
            </value>
            <value>
                <fullName>Alcohol swabs sterile</fullName>
            </value>
            <value>
                <fullName>Alcohol wipes PE bag</fullName>
            </value>
            <value>
                <fullName>Alcohol wipes tube</fullName>
            </value>
            <value>
                <fullName>Beard Cover</fullName>
            </value>
            <value>
                <fullName>Blunt Fill Needle With Filter</fullName>
            </value>
            <value>
                <fullName>Blunt Fill Needle/Hypodermic Needle</fullName>
            </value>
            <value>
                <fullName>Boot Covers</fullName>
            </value>
            <value>
                <fullName>Child Mask</fullName>
            </value>
            <value>
                <fullName>Disposable Bouffant Cap</fullName>
            </value>
            <value>
                <fullName>Disposable Face shield</fullName>
            </value>
            <value>
                <fullName>Disposable Shoe Covers</fullName>
            </value>
            <value>
                <fullName>Disposable Surgeon Cap</fullName>
            </value>
            <value>
                <fullName>Enteral Syringe</fullName>
            </value>
            <value>
                <fullName>EZ Wing</fullName>
            </value>
            <value>
                <fullName>Face Mask</fullName>
            </value>
            <value>
                <fullName>Finger Pulse Oximeter</fullName>
            </value>
            <value>
                <fullName>Fingertip Oximeter</fullName>
            </value>
            <value>
                <fullName>Flush Syringe - Saline</fullName>
            </value>
            <value>
                <fullName>Infrared Thermometers</fullName>
            </value>
            <value>
                <fullName>Instant hand sanitizer</fullName>
            </value>
            <value>
                <fullName>Instant hand sanitizer Gel</fullName>
            </value>
            <value>
                <fullName>Isolation Gowns</fullName>
            </value>
            <value>
                <fullName>KN95 Respirator</fullName>
            </value>
            <value>
                <fullName>Lab Coat</fullName>
            </value>
            <value>
                <fullName>Luer Adapter</fullName>
            </value>
            <value>
                <fullName>N95 Respirator</fullName>
            </value>
            <value>
                <fullName>Nitrile Glove</fullName>
            </value>
            <value>
                <fullName>Non-Safety Blood Collection Holder</fullName>
            </value>
            <value>
                <fullName>Non-Safety Butterfly Needle-VET</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UoM__c.field-meta.xml
<CustomField>
    <fullName>UoM__c</fullName>
    <label>UoM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>UN</fullName>
            </value>
            <value>
                <fullName>VOL</fullName>
            </value>
            <value>
                <fullName>CASE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <displayFormat>PRO-LINE-{0000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Animal Health</fullName>
    </customValue>
    <customValue>
        <fullName>Diabetes Care</fullName>
    </customValue>
    <customValue>
        <fullName>Gloves</fullName>
    </customValue>
    <customValue>
        <fullName>Hygiene Products</fullName>
    </customValue>
    <customValue>
        <fullName>Infusion</fullName>
    </customValue>
    <customValue>
        <fullName>Injection</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Medical System</fullName>
    </customValue>
    <customValue>
        <fullName>Medication Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>Oral, Enteral &amp; Irrigation Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Protective Apparel</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Anesthesia</fullName>
    </customValue>
    <customValue>
        <fullName>Sample Collection</fullName>
    </customValue>
    <customValue>
        <fullName>NEW PRODUCT</fullName>
    </customValue>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD &amp; RUP Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>AD &amp; RUP Syringe with Safety Arm</fullName>
    </customValue>
    <customValue>
        <fullName>Alcohol Swabs</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use Cassettes</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use IV Sets</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia needles</fullName>
    </customValue>
    <customValue>
        <fullName>Beard Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Collection Holders &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Collection Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Blunt Fill Needle &amp; Filter Needle</fullName>
    </customValue>
    <customValue>
        <fullName>Blunt Fill Needle Combo</fullName>
    </customValue>
    <customValue>
        <fullName>Bouffant Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Catheter dressing</fullName>
    </customValue>
    <customValue>
        <fullName>CGM System-Split Type</fullName>
    </customValue>
    <customValue>
        <fullName>Coverall</fullName>
    </customValue>
    <customValue>
        <fullName>Covid Test</fullName>
    </customValue>
    <customValue>
        <fullName>Devices for capillary blood collection</fullName>
    </customValue>
    <customValue>
        <fullName>Enteral Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pump Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pump Cassette</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Gloves</fullName>
    </customValue>
    <customValue>
        <fullName>Face shield</fullName>
    </customValue>
    <customValue>
        <fullName>Flush Syringe - Saline</fullName>
    </customValue>
    <customValue>
        <fullName>Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Heel Blood Lancets</fullName>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NACA_SAP_ProductBuilder.cls
public class NACA_SAP_ProductBuilder implements ISAP_ProductBuilder{
    private NACA_SAP_PARSER_Product wrapper;
    private Product2 product;

    public Product2 build(ISAP_PARSER wrapper){
        this.wrapper = (NACA_SAP_PARSER_Product) wrapper;
        this.product = new Product2();

        setProductName();
        setSAPCode();
        setProductCode();
        setCategories();
        setActive();
        setCurrency();
        setSellingUnits();

        return product;
    }

    public void setProductName(){
        product.Name = wrapper.ItemName;
    }

    public void setSAPCode(){
        product.SAP_Code__c = wrapper.ItemCode;
    }

    public void setProductCode(){
        product.ProductCode = wrapper.OldItemCode;
    }

    public void setCategories(){
        product.Family = wrapper.ItmsGrpNam;
        if( wrapper.Segment != null) product.Segment__c = wrapper.Segment;
        if( wrapper.ProductLine != null) product.Product_Line__c = wrapper.ProductLine;
        if( wrapper.Material != null) product.Material__c = wrapper.Material;
        if( wrapper.Branding != null)  product.Branding__c = wrapper.Branding;
        if( wrapper.Category != null) product.Category__c = wrapper.Category;
        if( wrapper.SubCategory != null) product.SubCategory__c = wrapper.SubCategory;
    }

    public void setActive(){
        product.IsActive = true;

        switch on wrapper.Active {
            when 'Y'{
                product.NACA_Active__c = true;
            }
            when else {
                product.NACA_Active__c = false;
            }
        }
    }

    public void setCurrency(){
        product.CurrencyIsoCode = 'USD';
    }

    public void setDimensions(){}

    public void setSellingUnits(){
        product.NACA_Case_Qty__c = Integer.valueOf(wrapper.NumInSale);
        product.NACA_Box_Quantity__c = !String.isBlank(wrapper.U_box_Qty) && wrapper.U_box_Qty.isNumeric() ? Integer.valueOf(wrapper.U_box_Qty) : null;
        product.UoM__c = wrapper.SalUnitMsr; //used in NACA quote template
    }
}