force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Default true for new Accounts created in Salesforce. Reflecting Business Partner status in SAP.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Default_Partner__c.field-meta.xml
<CustomField>
    <fullName>Default_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Default_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Forecast_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether the Forecasting feature is enabled for this Account.</description>
    <inlineHelpText>Determines whether the Forecasting feature is enabled for this Account.</inlineHelpText>
    <label>Forecasting Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Adjustment__c/Forecast_Adjustment__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Adjustment entry.</description>
    <label>Forecast Adjustment</label>
    <nameField>
        <label>Forecast Adjustment  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Adjustment__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Opportunity</label>
    <referenceTo>Forecast_Opportunity__c</referenceTo>
    <relationshipLabel>Forecast Adjustments</relationshipLabel>
    <relationshipName>Forecast_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <displayFormat>FI-{0000}</displayFormat>
        <label>Forecast Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/BU_Approval__c.field-meta.xml
<CustomField>
    <fullName>BU_Approval__c</fullName>
    <inlineHelpText>Dedicated for Item Type - Opportunity Product</inlineHelpText>
    <label>BU Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast Month</label>
    <referenceTo>Forecast_Month__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Adjustment</label>
    <referenceTo>Forecast_Adjustment__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <label>Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Product</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Current Order</fullName>
            </value>
            <value>
                <fullName>Previous Year Order</fullName>
            </value>
            <value>
                <fullName>Base</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/Forecast_Month__c.object-meta.xml
<CustomObject>
    <label>Forecast Month</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Forecast Moth</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Months</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Month__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Forecast_Product__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Forecast_Product__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Product__c</fullName>
    <label>Forecast Product</label>
    <referenceTo>Forecast_Product__c</referenceTo>
    <relationshipLabel>Forecast Months</relationshipLabel>
    <relationshipName>Forecast_Months</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Forecast_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <formula>Forecast_Product__r.Account__r.SAP_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/Forecast_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Opportunity Product.</description>
    <label>Forecast Opportunity</label>
    <nameField>
        <displayFormat>FO - {0000}</displayFormat>
        <label>Forecast Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Opportunity__c/fields/BU_Approval__c.field-meta.xml
<CustomField>
    <fullName>BU_Approval__c</fullName>
    <label>BU Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <label>Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <inlineHelpText>If empty on creation, value copied from Account.</inlineHelpText>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Incoterms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <inlineHelpText>If empty on creation, value copied from Account.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for Order in SAP</inlineHelpText>
    <label>SAP Code</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Fulfillment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Shipment</fullName>
    </customValue>
    <customValue>
        <fullName>Local Warehouse</fullName>
    </customValue>
    <masterLabel>Fulfillment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Incoterms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
    </customValue>
    <customValue>
        <fullName>DPU</fullName>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
    </customValue>
    <customValue>
        <fullName>CFR</fullName>
    </customValue>
    <masterLabel>Incoterms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ForecastExportBatch.cls
global class ForecastExportBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful  {

    @TestVisible static String payloadForTests;

    private Integer syncTime;

    global ForecastExportBatch(){
        this.syncTime = -2;
    }

    global ForecastExportBatch(Integer syncTime){
        this.syncTime = syncTime;
    }

	global Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator([
                SELECT id, Item_Type__c, Fulfillment__c, Quantity__c, Forecast__r.Month__c, External_Id__c, Active__c, BU_Approval__c,
                    Forecast__r.Forecast_Product__r.Local_Enabled__c,  Forecast__r.Forecast_Product__r.Direct_Enabled__c, Forecast__r.Forecast_Product__r.Local_Warehouse__r.Name,
                    Forecast__r.Forecast_Product__r.Account__r.Name, Forecast__r.Forecast_Product__r.Account__c, Forecast__r.Forecast_Product__r.Account__r.SAP_Code__c, 
                    Forecast__r.Forecast_Product__r.Account__r.Branch__c, Forecast__r.Forecast_Product__r.Account__r.Forecast_Enabled__c, 
                    Forecast__r.Forecast_Product__r.Account__r.Incoterms__c, Forecast__r.Forecast_Product__r.Account__r.Payment_Terms__c, 
                    Forecast__r.Forecast_Product__r.Account__r.RecordType.DeveloperName,
                    Forecast__r.Forecast_Product__r.Product__c, Forecast__r.Forecast_Product__r.Product__r.SAP_Code__c,
                    Forecast_Adjustment__r.Name,
                    Forecast__r.Forecast_Product__r.Account__r.Default_Partner__c, Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.Name, 
                    Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.SAP_Code__c, Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.Incoterms__c, 
                    Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.Payment_Terms__c, 
                    Forecast_Opportunity__r.Opportunity_Product__r.UnitPrice,
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Incoterms__c, Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Payment_Terms__c, 
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Name, Forecast_Opportunity__r.Opportunity_Product__r.PricebookEntry.Pricebook2.Name,
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.Name, Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__c, 
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.SAP_Code__c, 
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.Incoterms__c, Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.Payment_Terms__c
                FROM Forecast_Item__c 
                WHERE Item_Type__c NOT IN (:Constants.forecastItem.ITEM_TYPE_CURRENT_ORDER, :Constants.forecastItem.ITEM_TYPE_PREVIOUS_YEAR_ORDER)
                AND Forecast__r.Month__c >= :Date.today().toStartOfMonth()
                AND (
                    LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR
                    Forecast__r.Forecast_Product__r.Account__r.LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR
                    Forecast__r.Forecast_Product__r.LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR
                    Forecast_Adjustment__r.LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR
                    Forecast_Opportunity__r.LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR
                    Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.LastModifiedDate > :DateTime.now().addHours(this.syncTime) OR    
                    Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__R.LastModifiedDate > :DateTime.now().addHours(this.syncTime)                               
                )
                ORDER BY Forecast__r.Month__c
        ]);
	}

	global void execute(Database.BatchableContext bc, List<Forecast_Item__c> scope) {
        try {
            String payload = new ForecastExportBuilder(scope).build().serialize();

            if(Test.isRunningTest()){
                payloadForTests = payload;
            }
            
            if(!String.isEmpty(payload)){
                Http http = new Http();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('callout:' + 'DW/SFforecast');
                
                req.setMethod('POST');
                req.setHeader('Content-Type', 'application/json;charset=UTF-8');
                req.setBody(payload);
                req.setTimeout(120000); 
                system.debug('Forecast Batch Error Payload :' + payload);
                HttpResponse response = http.send(req);
                system.debug('Forecast Batch Error Request Details :' + req);
				system.debug('Forecast Batch Error Response :' + response);
                if(response.getStatusCode() != HttpStatusCode.OK) { 
                    new Logger('Forecast', 'POST').errorString(String.valueOf(response.getStatusCode()), response.getBody()).create();
                }  
            }         
        } catch (Exception e) {
            new Logger('Forecast', 'POST').error(e).create();
        }
	}

	global void finish(Database.BatchableContext bc) {

	}

    public class ForecastExportBuilder{
        List<ForecastExportWrapper> wrappers;
        List<Forecast_Item__c> forecastItems;

        public ForecastExportBuilder(List<Forecast_Item__c> scope){
            this.wrappers = new List<ForecastExportWrapper>();
            this.forecastItems = scope;
        }

        public ForecastExportBuilder build(){
            for(Forecast_Item__c item: forecastItems){
                ForecastExportWrapper wrapper = new ForecastExportWrapper(item);
                wrappers.add(wrapper.build());
            }
            return this;
        }

        public String serialize(){
            return JSON.serialize(wrappers);
        }
    }
}