force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Default true for new Accounts created in Salesforce. Reflecting Business Partner status in SAP.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Customer Group</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Interco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Invoicing Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marketing_Email__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Marketing Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MultiCurrency__c.field-meta.xml
<CustomField>
    <fullName>MultiCurrency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MultiCurrency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIP__c.field-meta.xml
<CustomField>
    <fullName>NIP__c</fullName>
    <label>NIP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Order_Realization_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Realization_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Order Realization Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <inlineHelpText>This field informs about specific type of organization - e.g. hospital, pharmacy, lab.</inlineHelpText>
    <label>Organization Type (Segment)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organization_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_Department_E_mail__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Department_E_mail__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Purchase Department E-mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Quality_Regulatory_Email__c.field-meta.xml
<CustomField>
    <fullName>Quality_Regulatory_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Quality &amp; Regulatory Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <inlineHelpText>Shipping Address zone. Synchronized with SAP.</inlineHelpText>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>Poland</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>German East, Czech Rep, Slovakia, Latvia, Lithuania</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Estonia, German West, Austria, Benelux, Italy North, Hungary</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Italy South</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Finland, Sweden</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Norway</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Spain East</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Spain West</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Portugal</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Ireland</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>UK</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Middle East</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Greece</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Romania, Bulgaria, Serbia, Kosovo</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Slovenia, Croatia</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Iceland</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Nigeria, Morocco</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>RPA</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Malta, Tenerife</label>
            </value>
            <value>
                <fullName>99</fullName>
                <label>All other (cost not supported, ie. China, USA, outside Europe)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Setting__mdt/SAP_Setting__mdt.object-meta.xml
<CustomObject>
    <label>SAP Setting</label>
    <pluralLabel>SAP Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAP_Setting__mdt/fields/Default_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Account_Owner__c</fullName>
    <description>Contains SlpCode to market default owner</description>
    <label>Default Account Owner</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Organization_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Buying Group</fullName>
    </customValue>
    <customValue>
        <fullName>City Hall</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmetic Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Drug Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Federal</fullName>
    </customValue>
    <customValue>
        <fullName>GP</fullName>
    </customValue>
    <customValue>
        <fullName>Health Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Health System</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Kit manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Market Place</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceutical Company</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Retail Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist Facility</fullName>
    </customValue>
    <customValue>
        <fullName>Vet Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Vet Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Company-Pharma</fullName>
    </customValue>
    <customValue>
        <fullName>Company-MedDev</fullName>
    </customValue>
    <customValue>
        <fullName>OEM-B2B-bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Distr-Hospital</fullName>
    </customValue>
    <customValue>
        <fullName>Distr-Retail</fullName>
    </customValue>
    <masterLabel>Organization Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EMEA_SAP_AccountBuilder.cls
public class EMEA_SAP_AccountBuilder implements ISAP_AccountBuilder {
    private Account acc;
    Map<String,Id> userSAPCodeMap;
    private EMEA_SAP_PARSER_Account wrapper;
    private SAP_Setting__mdt sapSetting;

    public EMEA_SAP_AccountBuilder(){}

    public void init(ISAP_PARSER wrapper, Map<String,Id> userSAPCodeMap, SAP_Setting__mdt sapSetting){
        this.acc = new Account(RecordTypeId = Constants.account.RECORD_TYPE_EMEA_ID);
        this.userSAPCodeMap = userSAPCodeMap;
        this.wrapper = (EMEA_SAP_PARSER_Account) wrapper;
        this.sapSetting = sapSetting;
    }

    public Account build(){
        setActive();
        setSAPCode();
        setOwner();
        setName();
        setNIP();
        setPhone();
        setCustomerStatus();
        setCurrency();
        setGroup();
        setOrganizationType();
        setIncoterms();
        setMarketingEmail();
        setInvoicingEmail();
        setOrderRealizationEmail();
        setPurchaseDepartmentEmail();
        setQualityRegulatoryEmail();
        setPaymentTermsCode();
        setBillingAddress();
        setShippingAddress();
        return acc;
    }

    public void setName(){
        acc.Name = wrapper.CardName;
    }

    public void setNIP(){
        acc.NIP__c = wrapper.LicTradNum;
    }

    public void setSAPCode(){
        acc.SAP_Code__c = 'SMPL-' + wrapper.CardCode;
    }

    public void setOwner(){
        if(Test.isRunningTest()){
            acc.OwnerId = UserInfo.getUserId();
            return;
        }

        if(!acc.Active__c) {
            acc.OwnerId = UserInfo.getUserId();
            return;
        }

        acc.OwnerId = userSAPCodeMap.get(String.valueOf(wrapper.SlpCode));
        if(acc.OwnerId == null){
            acc.OwnerId = userSAPCodeMap.get(String.valueOf(Integer.valueOf(sapSetting.Default_Account_Owner__c)));
        }
    }

    public String getSalesPersonCode(){
        return String.valueOf(wrapper.SlpCode);
    }

    public void setPhone(){
        acc.Phone = wrapper.Phone1;
    }

    public void setActive(){
        switch on wrapper.Active {
            when 'Y'{
                acc.Active__c = true;
            }
            when else {
                acc.Active__c = false;
            }
        }
    }

    public void setCustomerStatus(){
        acc.Customer_Status__c = Constants.account.CUSTOMER_STATUS_CUSTOMER;
    }

    public void setCurrency(){
        acc.MultiCurrency__c = false;
        switch on wrapper.CurrencyISO {
            when '##' {
                acc.CurrencyIsoCode = 'EUR';
                acc.MultiCurrency__c = true;
            }
            when '$' {
                acc.CurrencyIsoCode = 'USD';
            }
            when else {
                acc.CurrencyIsoCode = wrapper.CurrencyISO;
            }
        }
    }

    public void setGroup() {
        acc.Group__c = EMEA_SAP_Dictionary.GROUP_SAP_CODE_MAP.get(wrapper.GroupCode);
    }

    public void setOrganizationType() {
        acc.Organization_Type__c = EMEA_SAP_Dictionary.ORGANIZATION_TYPE_SAP_CODE_MAP.get(wrapper.Industry);
    }

    public void setIncoterms() {
        acc.Incoterms__c = wrapper.Incoterms;
    }

    public void setMarketingEmail() {
        acc.Marketing_Email__c = wrapper.MarketingEmail;
    }

    public void setInvoicingEmail() {
        acc.Invoicing_Email__c = wrapper.InvoicingEmail;
    }

    public void setOrderRealizationEmail() {
        acc.Order_Realization_Email__c = wrapper.OrderRealizationEmail;
    }

    public void setPurchaseDepartmentEmail() {
        acc.Purchase_Department_E_mail__c = wrapper.E_Mail;
    }

    public void setQualityRegulatoryEmail() {
        acc.Quality_Regulatory_Email__c = wrapper.QualityRegulatoryEmail;
    }

    public void setPaymentTermsCode() {
        acc.Payment_Terms__c = wrapper.PymntGroup;
    }

    public void setBillingAddress() {
        EMEA_SAP_PARSER_Account.BPAddresses billingAddress = getBillingAddress();

        if(billingAddress != null){
            acc.BillingCountryCode = billingAddress.Country;
            acc.BillingCity = billingAddress.City;
            acc.BillingStreet = billingAddress.Street;
            acc.BillingPostalCode = billingAddress.ZipCode;
        }
    }

    /*
        Business Partner in SAP should have one Billing Address
     */
    private EMEA_SAP_PARSER_Account.BPAddresses getBillingAddress(){
        for(EMEA_SAP_PARSER_Account.BPAddresses BPAddress: wrapper.BPAddresses){
            if(BPAddress.AdressType == 'B' && BPAddress.AddressName == wrapper.BillToDef){
                return BPAddress;
            }
        }
        return null;
    }
    /*
        Sync Shipping Address for Business Partner if one address present in SAP.
        If multiply - sync skipped
     */
    public void setShippingAddress(){
        EMEA_SAP_PARSER_Account.BPAddresses shippingAddress = getShippingAddress();

        if(shippingAddress != null){
            acc.ShippingCountryCode = shippingAddress.Country;
            acc.ShippingCity = shippingAddress.City;
            acc.ShippingStreet = shippingAddress.Street;
            acc.ShippingPostalCode = shippingAddress.ZipCode;

            if (shippingAddress.Zone != null || shippingAddress.Zone != '')
            {
                Integer intNum = Integer.valueOf(shippingAddress.Zone); // Convert to integer to remove leading zeros
                String strWithoutLeadingZeros = String.valueOf(intNum); // Convert back to string
                acc.Zone__c = strWithoutLeadingZeros;
            } else {
                acc.Zone__c = shippingAddress.Zone;
            }

            
        }
    }

    private EMEA_SAP_PARSER_Account.BPAddresses getShippingAddress(){
        List<EMEA_SAP_PARSER_Account.BPAddresses> shippingAddresses = new List<EMEA_SAP_PARSER_Account.BPAddresses>();

        for(EMEA_SAP_PARSER_Account.BPAddresses BPAddress: wrapper.BPAddresses){
            if(BPAddress.AdressType == 'S' && BPAddress.AddressName == wrapper.ShipToDef){
                return BPAddress;
            }
        }

        return null;
    }
}