force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Default true for new Accounts created in Salesforce. Reflecting Business Partner status in SAP.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Attention__c.field-meta.xml
<CustomField>
    <fullName>Attention__c</fullName>
    <description>Shipping</description>
    <label>Attention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <label>Billing Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Billing Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Phone__c.field-meta.xml
<CustomField>
    <fullName>Billing_Phone__c</fullName>
    <label>Billing Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Building_Floor__c.field-meta.xml
<CustomField>
    <fullName>Building_Floor__c</fullName>
    <label>Building/Floor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Carrier_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Name__c</fullName>
    <label>Carrier Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>IDN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Notification_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Delivery Notification Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Federal_Tax_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id_Number__c</fullName>
    <label>EIN/BN Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Customer Group</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Interco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/In_business_since__c.field-meta.xml
<CustomField>
    <fullName>In_business_since__c</fullName>
    <label>In business since</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Invoicing Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Maximum_Pallet_Height__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Pallet_Height__c</fullName>
    <label>Maximum Pallet Height</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Order_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Confirmation_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Order Confirmation Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_Department_E_mail__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Department_E_mail__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Purchase Department E-mail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Receiving_Hours__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Hours__c</fullName>
    <label>Receiving Hours</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Tax_Exempt_Account__c.field-meta.xml
<CustomField>
    <fullName>Sales_Tax_Exempt_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This is the field to indicate whether an account is tax exempt.
If it is check as True, You must Upload the respective document into Files list.</inlineHelpText>
    <label>Sales Tax Exempt Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Name__c</fullName>
    <label>Shipping Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Email__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Email__c</fullName>
    <inlineHelpText>For multiply emails, separate them with semicolon.</inlineHelpText>
    <label>Shipping Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Number__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Number__c</fullName>
    <label>Shipping Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shipping_Phone__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Phone__c</fullName>
    <label>Shipping Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Suite_Room__c.field-meta.xml
<CustomField>
    <fullName>Suite_Room__c</fullName>
    <label>Suite/Room</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/X810_Invoice__c.field-meta.xml
<CustomField>
    <fullName>X810_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>810 – Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X850_Orders__c.field-meta.xml
<CustomField>
    <fullName>X850_Orders__c</fullName>
    <defaultValue>false</defaultValue>
    <label>850 - Orders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X855_Order_Acknowledgement__c.field-meta.xml
<CustomField>
    <fullName>X855_Order_Acknowledgement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>855 – Order Acknowledgement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X856_Advanced_Ship_Notice__c.field-meta.xml
<CustomField>
    <fullName>X856_Advanced_Ship_Notice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>856 – Advanced Ship Notice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_Setting__mdt/SAP_Setting__mdt.object-meta.xml
<CustomObject>
    <label>SAP Setting</label>
    <pluralLabel>SAP Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAP_Setting__mdt/fields/Default_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Default_Account_Owner__c</fullName>
    <description>Contains SlpCode to market default owner</description>
    <label>Default Account Owner</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NACA_SAP_AccountBuilder.cls
public class NACA_SAP_AccountBuilder implements ISAP_AccountBuilder {
    private Account acc;
    Map<String,Id> userSAPCodeMap;
    private NACA_SAP_PARSER_Account wrapper;
    private SAP_Setting__mdt sapSetting;

    public NACA_SAP_AccountBuilder(){}

    public void init(ISAP_PARSER wrapper, Map<String,Id> userSAPCodeMap, SAP_Setting__mdt sapSetting){
        this.acc = new Account(RecordTypeId = Constants.account.RECORD_TYPE_NACA_ID);
        this.userSAPCodeMap = userSAPCodeMap;
        this.wrapper = (NACA_SAP_PARSER_Account) wrapper;
        this.sapSetting = sapSetting;
    }

    public Account build(){
        setGroup();
        setActive();
        setSAPCode();
        setOwner();
        setName();
        setPhone();
        setCustomerStatus();
        setCurrency();
        setFederalTaxId();
        setInBusinessSince();
        setTaxExemptAccount();
        setPurchaseDepartmentEmail();
        setOrderConfirmationEmail();
        setDeliveryConfirmationEmail();
        setSendingInvoicesEmail();
        setPaymentTermsCode();
        setBillingAddress();
        setBillingContactInfo();
        setShippingAddress();
        setShippingContactInfo();
        setEdiOptions();
        return acc;
    }

    public void setGroup() {
        acc.Group__c = NACA_SAP_Dictionary.GROUP_SAP_CODE_MAP.get(wrapper.GroupCode);
    }

    public void setActive(){
        switch on wrapper.Active {
            when 'Y'{
                acc.Active__c = true;
            }
            when else {
                acc.Active__c = false;
            }
        }
    }

    public void setName(){
        acc.Name = wrapper.CardName;
    }

    public void setSAPCode(){
        acc.SAP_Code__c = 'NACA-' + wrapper.CardCode;
    }

    public void setOwner(){
        acc.OwnerId = userSAPCodeMap.get(String.valueOf(wrapper.SlpCode));

        if(Test.isRunningTest()){
            acc.OwnerId = UserInfo.getUserId();
            return;
        }

        if(acc.OwnerId == null){
            acc.OwnerId = userSAPCodeMap.get(String.valueOf(sapSetting.Default_Account_Owner__c));
        }
    }

    public String getSalesPersonCode(){
        return String.valueOf(wrapper.SlpCode);
    }

    public void setPhone(){
        acc.Phone = wrapper.Phone1;
       
    }

    public void setCustomerStatus(){
        acc.Customer_Status__c = Constants.account.CUSTOMER_STATUS_CUSTOMER;
    }

    public void setCurrency(){
        acc.CurrencyIsoCode = 'USD';
    }

    public void setFederalTaxId(){
        acc.Federal_Tax_Id_Number__c = wrapper.FederalTaxIdNumber;
    }

    public void setInBusinessSince(){
        if(wrapper.InBusinessSince != '0'){
            acc.In_business_since__c = wrapper.InBusinessSince;
        }
    }

    public void setTaxExemptAccount(){
        acc.Sales_Tax_Exempt_Account__c = getBooleanValue(wrapper.TaxExemptAccount);
    }
    
    public void setPurchaseDepartmentEmail(){
        acc.Purchase_Department_E_mail__c = wrapper.E_Mail;
    }

    public void setOrderConfirmationEmail(){
        acc.Order_Confirmation_Email__c = wrapper.OrderConfirmationEmail;
    }

    public void setDeliveryConfirmationEmail(){
        acc.Delivery_Notification_Email__c = wrapper.DeliveryNotificationEmail;
    }
    
    public void setSendingInvoicesEmail(){
        acc.Invoicing_Email__c = wrapper.SendingInvoicesEmail;
    }

    public void setPaymentTermsCode(){
        acc.Payment_Terms__c = wrapper.PymntGroup;
    }

    public void setBillingAddress(){
        NACA_SAP_PARSER_Account.BPAddresses billingAddress = getBillingAddress();

        if(billingAddress != null){
            acc.BillingCountryCode = billingAddress.Country;
            acc.BillingCity = billingAddress.City;
            acc.BillingStreet = billingAddress.Street;
            acc.BillingPostalCode = billingAddress.ZipCode;

            if(billingAddress.Country == 'US' || billingAddress.Country == 'CA') {
                acc.BillingStateCode = billingAddress.State;
            }
        }
    }

    /*
        Business Partner in SAP should have one Billing Address
     */
    private NACA_SAP_PARSER_Account.BPAddresses getBillingAddress(){
        for(NACA_SAP_PARSER_Account.BPAddresses BPAddress: wrapper.BPAddresses){
            if(BPAddress.AdressType == 'B'){
                return BPAddress;
            }
        }
        return null;
    }

    public void setBillingContactInfo(){
        NACA_SAP_PARSER_Account.ContactEmployees billingContact = getContactInfo('Billing Agent');

        if(billingContact != null){
            acc.Billing_Contact_Name__c = billingContact.FirstName + ' ' + billingContact.LastName;
            acc.Billing_Email__c = billingContact.E_MailL;
            acc.Billing_Phone__c = billingContact.Tel1;
        }
    }

    /*
        Sync Shipping Address for Business Partner if one address present in SAP.
        If multiply - sync skipped
     */
    public void setShippingAddress(){
        NACA_SAP_PARSER_Account.BPAddresses shippingAddress = getShippingAddress();

        if(shippingAddress != null){
            acc.ShippingCountryCode = shippingAddress.Country;
            acc.ShippingCity = shippingAddress.City;
            acc.ShippingStreet = shippingAddress.Street;
            acc.ShippingPostalCode = shippingAddress.ZipCode;

            if(shippingAddress.Country == 'US' || shippingAddress.Country == 'CA') {
                acc.ShippingStateCode = shippingAddress.State;
            }

            acc.Attention__c = shippingAddress.Block;
            acc.Suite_Room__c = shippingAddress.StreetNo;
            acc.Building_Floor__c = shippingAddress.Building;
            acc.Carrier_Name__c = shippingAddress.U_CCarrierName;
            acc.Shipping_Number__c = shippingAddress.U_CAccount;
            acc.Maximum_Pallet_Height__c = shippingAddress.U_CMaxPalletHeight;
            acc.Receiving_Hours__c = shippingAddress.U_CReceivingHours;
            acc.GLN__c = shippingAddress.GlobalLocationNumber;         
        }
    }

    private NACA_SAP_PARSER_Account.BPAddresses getShippingAddress(){
        List<NACA_SAP_PARSER_Account.BPAddresses> shippingAddresses = new List<NACA_SAP_PARSER_Account.BPAddresses>();

        for(NACA_SAP_PARSER_Account.BPAddresses BPAddress: wrapper.BPAddresses){
            if(BPAddress.AdressType == 'S'){
                shippingAddresses.add(BPAddress);
            }
        }

        if(shippingAddresses.size() == 1){
            return shippingAddresses[0];
        }

        return null;
    }

    public void setShippingContactInfo(){
        NACA_SAP_PARSER_Account.ContactEmployees shippingContact = getContactInfo('Purchasing Agent');
        if(shippingContact != null){
            acc.Shipping_Contact_Name__c = shippingContact.FirstName + ' ' + shippingContact.LastName;
            acc.Shipping_Email__c = shippingContact.E_MailL;
            acc.Shipping_Phone__c = shippingContact.Tel1;
        }    
    }

    private NACA_SAP_PARSER_Account.ContactEmployees getContactInfo(String contactIdName){
        for(NACA_SAP_PARSER_Account.ContactEmployees ContactEmployee: wrapper.ContactEmployees){
            if(ContactEmployee.Name == contactIdName){
                return ContactEmployee;
            }
        }
        return null;
    }

    public void setEdiOptions(){
        acc.X810_Invoice__c = getBooleanValue(wrapper.SPSSendInvoice); 
        acc.X850_Orders__c = getBooleanValue(wrapper.SPSOrderStandAlone); 
        acc.X855_Order_Acknowledgement__c = getBooleanValue(wrapper.SPSSendPOAck); 
        acc.X856_Advanced_Ship_Notice__c = getBooleanValue(wrapper.SPSSendASN); 
       
    }

    private Boolean getBooleanValue(String entry){
        if(entry != null && entry == 'Y'){
            return true;
        }
        return false;
    }
}