force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Default true for new Accounts created in Salesforce. Reflecting Business Partner status in SAP.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Forecast_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether the Forecasting feature is enabled for this Account.</description>
    <inlineHelpText>Determines whether the Forecasting feature is enabled for this Account.</inlineHelpText>
    <label>Forecasting Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Adjustment__c/Forecast_Adjustment__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Adjustment entry.</description>
    <label>Forecast Adjustment</label>
    <nameField>
        <label>Forecast Adjustment  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Adjustment__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Opportunity</label>
    <referenceTo>Forecast_Opportunity__c</referenceTo>
    <relationshipLabel>Forecast Adjustments</relationshipLabel>
    <relationshipName>Forecast_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <displayFormat>FI-{0000}</displayFormat>
        <label>Forecast Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/BU_Approval__c.field-meta.xml
<CustomField>
    <fullName>BU_Approval__c</fullName>
    <inlineHelpText>Dedicated for Item Type - Opportunity Product</inlineHelpText>
    <label>BU Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast Month</label>
    <referenceTo>Forecast_Month__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Adjustment</label>
    <referenceTo>Forecast_Adjustment__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forecast Opportunity</label>
    <referenceTo>Forecast_Opportunity__c</referenceTo>
    <relationshipLabel>Forecast Items</relationshipLabel>
    <relationshipName>Forecast_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <label>Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity Product</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Current Order</fullName>
            </value>
            <value>
                <fullName>Previous Year Order</fullName>
            </value>
            <value>
                <fullName>Base</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/Forecast_Month__c.object-meta.xml
<CustomObject>
    <label>Forecast Month</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Forecast Moth</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Months</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Month__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Forecast_Product__r.Account__r.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Forecast_Product__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Product__c</fullName>
    <label>Forecast Product</label>
    <referenceTo>Forecast_Product__c</referenceTo>
    <relationshipLabel>Forecast Months</relationshipLabel>
    <relationshipName>Forecast_Months</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>Forecast_Product__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Month__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <formula>Forecast_Product__r.Account__r.SAP_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/Forecast_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Forecast Item with Opportunity Product.</description>
    <label>Forecast Opportunity</label>
    <nameField>
        <displayFormat>FO - {0000}</displayFormat>
        <label>Forecast Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Opportunity__c/fields/BU_Approval__c.field-meta.xml
<CustomField>
    <fullName>BU_Approval__c</fullName>
    <label>BU Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <label>Fulfillment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Opportunity__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Forecast Opportunities</relationshipLabel>
    <relationshipName>Forecast_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterms__c.field-meta.xml
<CustomField>
    <fullName>Incoterms__c</fullName>
    <inlineHelpText>If empty on creation, value copied from Account.</inlineHelpText>
    <label>Incoterms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Incoterms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <inlineHelpText>If empty on creation, value copied from Account.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Fulfillment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Shipment</fullName>
    </customValue>
    <customValue>
        <fullName>Local Warehouse</fullName>
    </customValue>
    <masterLabel>Fulfillment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Incoterms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>FOB</fullName>
    </customValue>
    <customValue>
        <fullName>DAP</fullName>
    </customValue>
    <customValue>
        <fullName>DDP</fullName>
    </customValue>
    <customValue>
        <fullName>EXW</fullName>
    </customValue>
    <customValue>
        <fullName>FCA</fullName>
    </customValue>
    <customValue>
        <fullName>CPT</fullName>
    </customValue>
    <customValue>
        <fullName>CIP</fullName>
    </customValue>
    <customValue>
        <fullName>DPU</fullName>
    </customValue>
    <customValue>
        <fullName>FAS</fullName>
    </customValue>
    <customValue>
        <fullName>CFR</fullName>
    </customValue>
    <masterLabel>Incoterms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ForecastExportWrapper.cls
public class ForecastExportWrapper{
    public String ExternalId; 
    public String AccountCode;
    public String AccountName;
    public String AccountIncoterms;
    public String AccountPaymentTerms;
    public String Country;
    public String Branch;
    public String ProductCode;
    public String ForecastStatus;
    public String ShipmentMethod;
    public String Warehouse;
    public String DemandType;
    public String OpportunityName;
    public String AdjustmentName;
    public String FulfillmentDate;
    public String Quantity;
    public String OpportunityPricebook;
    public String OpportunityPrice;
    public String PartnerName;
    public String PartnerCode;
    public String PartnerIncoterms;
    public String PartnerPaymentTerms;

    transient private Forecast_Item__c item;

    public ForecastExportWrapper(Forecast_Item__c item){
        this.item = item;
    }

    public ForecastExportWrapper build(){
        setExternalId();
        setAccountDetails();
        setBranchInfo();
        setProductInfo();
        this.ForecastStatus = checkForecastStatus() ? 'Active' : 'Inactive';
        setForecastInfo();
        setOpportunityInfo();
        setAdjustmentInfo();
        setPartnerDetails();
        return this;
    }

    private void setExternalId(){
        this.ExternalId = item.External_Id__c;
    }

    private void setAccountDetails(){
        this.AccountCode = item.Forecast__r.Forecast_Product__r.Account__r.SAP_Code__c?.substringAfter('-');
        this.AccountName = item.Forecast__r.Forecast_Product__r.Account__r.Name;
        this.AccountIncoterms = item?.Forecast_Opportunity__r?.Opportunity_Product__r?.Opportunity.Incoterms__c 
            == null ? item.Forecast__r.Forecast_Product__r.Account__r.Incoterms__c : item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Incoterms__c; 
        this.AccountPaymentTerms = item?.Forecast_Opportunity__r?.Opportunity_Product__r?.Opportunity.Payment_Terms__c 
            == null ? item.Forecast__r.Forecast_Product__r.Account__r.Payment_Terms__c : item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Payment_Terms__c; 
    }

    private void setBranchInfo(){
        this.Country = item.Forecast__r.Forecast_Product__r.Account__r.Branch__c;
        this.Branch = item.Forecast__r.Forecast_Product__r.Account__r.RecordType.DeveloperName == Constants.account.RECORD_TYPE_NACA ? Constants.account.BRANCH_NACA : Constants.account.BRANCH_EMEA;
    }

    private void setProductInfo(){
        this.ProductCode = item.Forecast__r.Forecast_Product__r.Product__r.SAP_Code__c;
    }

    private void setForecastInfo(){
        this.ShipmentMethod = item.Fulfillment__c;
        this.Warehouse = item.Fulfillment__c == Constants.forecastItem.FULFILLMENT_DIRECT ? Constants.forecastItem.WAREHOUSE_DIRECT_CODE : item.Forecast__r.Forecast_Product__r?.Local_Warehouse__r.Name;
        this.DemandType = item.Item_Type__c;
        this.FulfillmentDate = String.valueOf(item.Forecast__r.Month__c);
        this.Quantity = String.valueOf(item.Quantity__c);
    }

    private Boolean checkForecastStatus(){
        if(!item.Active__c){
            return false;
        }else if(!item.Forecast__r.Forecast_Product__r.Account__r.Forecast_Enabled__c){
            return false;
        }else if(item.Fulfillment__c == Constants.forecastItem.FULFILLMENT_DIRECT && !item.Forecast__r.Forecast_Product__r.Direct_Enabled__c){
            return false;
        }else if(item.Fulfillment__c == Constants.forecastItem.FULFILLMENT_LOCAL && !item.Forecast__r.Forecast_Product__r.Local_Enabled__c){
            return false;
        }else if(item.Item_Type__c == Constants.forecastItem.ITEM_TYPE_OPP_PRODUCT && item.BU_Approval__c != Constants.approval.APPROVED){
            return false;
        }else if(item.Item_Type__c == Constants.forecastItem.ITEM_TYPE_OPP_PRODUCT && item.Forecast_Opportunity__r.Opportunity_Product__c == null){
            return false;
        }
        return true;
    }

    private void setOpportunityInfo(){
        this.OpportunityName = item?.Forecast_Opportunity__r?.Opportunity_Product__r?.Opportunity.Name; 
        this.OpportunityPricebook = item?.Forecast_Opportunity__r?.Opportunity_Product__r?.PricebookEntry?.Pricebook2.Name;
        this.OpportunityPrice = String.valueOf(item?.Forecast_Opportunity__r?.Opportunity_Product__r?.UnitPrice != null ? item.Forecast_Opportunity__r.Opportunity_Product__r.UnitPrice : 0);
    }

    private void setAdjustmentInfo(){
        this.AdjustmentName = item?.Forecast_Adjustment__r.Name;
    }

    private void setPartnerDetails(){
        if(item?.Forecast_Opportunity__r?.Opportunity_Product__r?.Opportunity.Business_Partner__c != null){
            this.PartnerName = item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.Name;
            this.PartnerCode = item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.SAP_Code__c?.substringAfter('-');
            this.PartnerIncoterms = item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.Incoterms__c;
            this.PartnerPaymentTerms = item.Forecast_Opportunity__r.Opportunity_Product__r.Opportunity.Business_Partner__r.Payment_Terms__c;
        }else if(item.Forecast__r.Forecast_Product__r.Account__r.Default_Partner__c != null){
            this.PartnerName = item.Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.Name;
            this.PartnerCode = item.Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.SAP_Code__c?.substringAfter('-');
            this.PartnerIncoterms = item.Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.Incoterms__c;
            this.PartnerPaymentTerms = item.Forecast__r.Forecast_Product__r.Account__r.Default_Partner__r.Payment_Terms__c;
        }
    }
}