force-app/main/default/objects/Account/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <label>Billing Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Federal_Tax_Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id_Number__c</fullName>
    <label>EIN/BN Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <inlineHelpText>Customer Group</inlineHelpText>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Interco</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_Type__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type__c</fullName>
    <inlineHelpText>This field informs about specific type of organization - e.g. hospital, pharmacy, lab.</inlineHelpText>
    <label>Organization Type (Segment)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organization_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% Prepayment</fullName>
            </value>
            <value>
                <fullName>100% COD</fullName>
            </value>
            <value>
                <fullName>100% prepayment before production</fullName>
            </value>
            <value>
                <fullName>100% prepayment before shipment</fullName>
            </value>
            <value>
                <fullName>Net7-C</fullName>
            </value>
            <value>
                <fullName>Net14-C</fullName>
            </value>
            <value>
                <fullName>Net30-C</fullName>
            </value>
            <value>
                <fullName>Net45-C</fullName>
            </value>
            <value>
                <fullName>Net60-C</fullName>
            </value>
            <value>
                <fullName>Net90-C</fullName>
            </value>
            <value>
                <fullName>Net120-C</fullName>
            </value>
            <value>
                <fullName>Letter of Credit</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% COD</fullName>
            </value>
            <value>
                <fullName>30% Prepayment, 70% Net30-C</fullName>
            </value>
            <value>
                <fullName>50% Net30C + 50% Net60-C</fullName>
            </value>
            <value>
                <fullName>50% Prepayment, 50% COD</fullName>
            </value>
            <value>
                <fullName>80% prepayment, 20% ship</fullName>
            </value>
            <value>
                <fullName>Payment at delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>This field informs about organization sector - privater, public or retail.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Organization_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Buying Group</fullName>
    </customValue>
    <customValue>
        <fullName>City Hall</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmetic Surgery</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Drug Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Estate</fullName>
    </customValue>
    <customValue>
        <fullName>Federal</fullName>
    </customValue>
    <customValue>
        <fullName>GP</fullName>
    </customValue>
    <customValue>
        <fullName>Health Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Health System</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Kit manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>Lab</fullName>
    </customValue>
    <customValue>
        <fullName>Market Place</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmaceutical Company</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Retail Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Specialist Facility</fullName>
    </customValue>
    <customValue>
        <fullName>Vet Clinic</fullName>
    </customValue>
    <customValue>
        <fullName>Vet Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Company-Pharma</fullName>
    </customValue>
    <customValue>
        <fullName>Company-MedDev</fullName>
    </customValue>
    <customValue>
        <fullName>OEM-B2B-bulk</fullName>
    </customValue>
    <customValue>
        <fullName>Distr-Hospital</fullName>
    </customValue>
    <customValue>
        <fullName>Distr-Retail</fullName>
    </customValue>
    <masterLabel>Organization Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Public</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountToMuleTest.cls
@isTest
public class AccountToMuleTest {

    @TestSetup
    static void setup() {

        Account account = new Account(
            Name = 'Sol Millennium Medical Inc. 123',
            Phone = '5555555',
            ShippingCountry = 'US',
            //ShippingState = 'LA',
            ShippingCity = 'LA',
            ShippingStreet = '311 South Wacker Drive, Suite – 4100, Chicago - 60606',
            BillingCountry = 'US',
            //BillingState = 'LA',
            BillingCity = 'LA',
            BillingStreet = '311 South Wacker Drive, Suite – 4100, Chicago - 60606',
            BillingPostalCode = '123456',
            //Billing_Contact_Name__c = 
            SAP_Code__c = 'CIC00015',
            Payment_Terms__c = 'Net50-C',
            Incoterms__c = 'CIF',
            Sector__c = 'Public',
            Organization_Type__c = 'Hospital',
            Federal_Tax_Id_Number__c = 'abc123',
            
            Type = 'Customer'
        );
        insert account;
    }
    
    @isTest
    static void testAccountInsert() {
        
        Test.startTest();
        List<Account> acc = [SELECT 
                                Id, Name, SAP_Code__c, OwnerId, Type,                              		
                                Phone, Industry, Group__c,  
                                BillingCountryCode, BillingState, BillingStateCode, BillingCity, 
                                BillingPostalCode, BillingStreet,                                     
                                ShippingCountryCode, ShippingState, ShippingStateCode, ShippingCity, 
                                ShippingPostalCode, ShippingStreet, RecordTypeId                                     
                                FROM Account WHERE SAP_Code__c = 'CIC00015' LIMIT 1];

        Test.stopTest();

    }
}