force-app/main/default/objects/Forecast_Product__c/Forecast_Product__c.object-meta.xml
<CustomObject>
    <label>Forecast Product</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forecast Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Direct_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Direct_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Local_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Local_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Local Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SetForecastProductWrapperTest.cls
@IsTest
private class SetForecastProductWrapperTest {
	@IsTest
	static void setFulfillmentByForecastProductTest() {
		Forecast_Product__c forecastProduct = new Forecast_Product__c(
				Account__c = TestUtility.getFakeId(Schema.Account.getSObjectType()),
				Product__c = TestUtility.getFakeId(Schema.Product2.getSObjectType()),
				Local_Enabled__c = true,
				Direct_Enabled__c = true
		);

		SetForecastProductWrapper productWrapper = new SetForecastProductWrapper().setFulfillmentByForecastProduct(forecastProduct);
		System.assert(productWrapper.isLocalEnabled);
		System.assert(productWrapper.isDirectEnabled);
		System.assertEquals('Yes', productWrapper.directEnabled);
		System.assertEquals('Yes', productWrapper.localEnabled);

		forecastProduct.Local_Enabled__c = false;
		productWrapper.setFulfillmentByForecastProduct(forecastProduct);
		System.assert(!productWrapper.isLocalEnabled);
		System.assertEquals('No', productWrapper.localEnabled);
		System.assert(productWrapper.isDirectEnabled);
		System.assertEquals('Yes', productWrapper.directEnabled);

		forecastProduct.Local_Enabled__c = true;
		forecastProduct.Direct_Enabled__c = false;
		productWrapper.setFulfillmentByForecastProduct(forecastProduct);
		System.assert(productWrapper.isLocalEnabled);
		System.assertEquals('Yes', productWrapper.localEnabled);
		System.assert(!productWrapper.isDirectEnabled);
		System.assertEquals('No', productWrapper.directEnabled);
	}
}