force-app/main/default/objects/Forecast_Product__c/Forecast_Product__c.object-meta.xml
<CustomObject>
    <label>Forecast Product</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forecast Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Product__c/fields/Direct_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Direct_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Local_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Local_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Local Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Product Line</label>
    <nameField>
        <displayFormat>PRO-LINE-{0000}</displayFormat>
        <label>Product Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD &amp; RUP Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>AD &amp; RUP Syringe with Safety Arm</fullName>
    </customValue>
    <customValue>
        <fullName>Alcohol Swabs</fullName>
    </customValue>
    <customValue>
        <fullName>Allergy Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use Cassettes</fullName>
    </customValue>
    <customValue>
        <fullName>Ambulatory Pump Use IV Sets</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesia needles</fullName>
    </customValue>
    <customValue>
        <fullName>Beard Cover</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Collection Holders &amp; Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Collection Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Blood Pressure Monitors</fullName>
    </customValue>
    <customValue>
        <fullName>Blunt Fill Needle &amp; Filter Needle</fullName>
    </customValue>
    <customValue>
        <fullName>Blunt Fill Needle Combo</fullName>
    </customValue>
    <customValue>
        <fullName>Bouffant Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Catheter dressing</fullName>
    </customValue>
    <customValue>
        <fullName>CGM System-Split Type</fullName>
    </customValue>
    <customValue>
        <fullName>Coverall</fullName>
    </customValue>
    <customValue>
        <fullName>Covid Test</fullName>
    </customValue>
    <customValue>
        <fullName>Devices for capillary blood collection</fullName>
    </customValue>
    <customValue>
        <fullName>Enteral Syringe</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pump Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pump Cassette</fullName>
    </customValue>
    <customValue>
        <fullName>Epidural Ambulatory Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Gloves</fullName>
    </customValue>
    <customValue>
        <fullName>Face shield</fullName>
    </customValue>
    <customValue>
        <fullName>Flush Syringe - Saline</fullName>
    </customValue>
    <customValue>
        <fullName>Gowns</fullName>
    </customValue>
    <customValue>
        <fullName>Heel Blood Lancets</fullName>
    </customValue>
    <masterLabel>Product Line</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SetForecastProductWrapper.cls
public with sharing class SetForecastProductWrapper {
	@AuraEnabled public Id opportunityLineItemId { get; set; }
	@AuraEnabled public Id productId { get; set; }
	@AuraEnabled public Id accountId { get; set; }
	@AuraEnabled public Id forecastOpportunityDirectId { get; set; }
	@AuraEnabled public Id forecastOpportunityLocalId { get; set; }
	@AuraEnabled public Id forecastProductId { get; set; }

	@AuraEnabled public String currencyIsoCode { get; set; }
	@AuraEnabled public String productName { get; set; }
	@AuraEnabled public String productLine { get; set; }
	@AuraEnabled public String productCode { get; set; }
	@AuraEnabled public String volume { get; set; }
	@AuraEnabled public Decimal caseQuantity { get; set; }
	@AuraEnabled public Boolean isDirectEnabled { get; set; }
	@AuraEnabled public Boolean isLocalEnabled { get; set; }
	@AuraEnabled public String directEnabled { get; set; }
	@AuraEnabled public String localEnabled { get; set; }
	@AuraEnabled public String comment { get; set; }
	@AuraEnabled public String commentDirect { get; set; }
	@AuraEnabled public String commentLocal { get; set; }
	@AuraEnabled public String fulfillment { get; set; }

	@AuraEnabled public List<SetForecastScheduleWrapper> scheduleWrappers { get; set; }

	public final String FULFILLMENT_DIRECT_SHIPMENT_COMBOBOX_VALUE = 'directShipment';
	public final String FULFILLMENT_LOCAL_WAREHOUSE_COMBOBOX_VALUE = 'localWarehouse';

	public final Map<String,String> FULFILLMENT_PICKLIST_BY_COMBOBOX_VALUE = new Map<String,String> {
			FULFILLMENT_DIRECT_SHIPMENT_COMBOBOX_VALUE => Constants.forecastItem.FULFILLMENT_DIRECT,
			FULFILLMENT_LOCAL_WAREHOUSE_COMBOBOX_VALUE => Constants.forecastItem.FULFILLMENT_LOCAL
	};

	public SetForecastProductWrapper buildWithoutForecastProductData(OpportunityLineItem oli, Id accountId, String quantityFieldAPINAme, String volume) {
		this.opportunityLineItemId = oli.Id;
		this.productId = oli.Product2Id;
		this.accountId = accountId;
		this.productName = oli.Product2?.Name;
		this.productLine = oli.Product2?.Product_Line__c;
		this.productCode = oli.Product2?.ProductCode;
		this.currencyIsoCode = oli.CurrencyIsoCode;
		this.caseQuantity = (Decimal) oli.Product2?.get(quantityFieldAPINAme);
		this.volume = volume;
		return this;
	}

	public SetForecastProductWrapper setFulfillmentByForecastProduct(Forecast_Product__c forecastProduct) {
		this.forecastProductId = forecastProduct.Id;
		if (forecastProduct.Local_Enabled__c) {
			this.isLocalEnabled = true;
			this.localEnabled = OpportunitySetForecastHandler.YES;
		} else {
			this.isLocalEnabled = false;
			this.localEnabled = OpportunitySetForecastHandler.NO;
		}
		if (forecastProduct.Direct_Enabled__c) {
			this.isDirectEnabled = true;
			this.directEnabled = OpportunitySetForecastHandler.YES;
		} else {
			this.isDirectEnabled = false;
			this.directEnabled = OpportunitySetForecastHandler.NO;
		}
		return this;
	}

	public SetForecastProductWrapper setForecastOpportunityData(Id forecastOppId, String comment, String fulfillment) {
		if(fulfillment == Constants.forecastItem.FULFILLMENT_DIRECT) {
			this.fulfillment = FULFILLMENT_DIRECT_SHIPMENT_COMBOBOX_VALUE;
			this.commentDirect = comment;
			this.forecastOpportunityDirectId = forecastOppId;
		} else {
			this.fulfillment = FULFILLMENT_LOCAL_WAREHOUSE_COMBOBOX_VALUE;
			this.commentLocal = comment;
			this.forecastOpportunityLocalId = forecastOppId;
		}
		return this;
	}

	public Id getForecastOpportunityIdByFulfillment() {
		if(this.fulfillment == FULFILLMENT_DIRECT_SHIPMENT_COMBOBOX_VALUE) {
			return this.forecastOpportunityDirectId;
		} else {
			return this.forecastOpportunityLocalId;
		}
	}

	public String getFulfillmentPicklistName() {
		return FULFILLMENT_PICKLIST_BY_COMBOBOX_VALUE.get(this.fulfillment);
	}
}