force-app/main/default/objects/Forecast_Product__c/Forecast_Product__c.object-meta.xml
<CustomObject>
    <label>Forecast Product</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Forecast Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Direct_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Direct_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Direct Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Local_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Local_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Local Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Forecast Products</relationshipLabel>
    <relationshipName>Forecast_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/EMEA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>EMEA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for EMEA region.</inlineHelpText>
    <label>EMEA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NACA_Case_Qty__c.field-meta.xml
<CustomField>
    <fullName>NACA_Case_Qty__c</fullName>
    <inlineHelpText>Case Quantity for NACA region.</inlineHelpText>
    <label>NACA Case Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ForecastLookupProductCtrl.cls
public with sharing class ForecastLookupProductCtrl {
    private final static Integer MAX_RESULTS = 10;
    private static final string PRODUCT2_ICON = 'standard:product';

    @AuraEnabled
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds, String accountId) {
        List<List<SObject>> searchResults = [
            FIND :searchTerm
            IN ALL FIELDS
            RETURNING
                Product2(Id, Name, ProductCode, NACA_Case_Qty__c, EMEA_Case_Qty__c, SAP_Code__c WHERE Id NOT IN :selectedIds 
                    AND Id NOT IN (SELECT Product__c FROM Forecast_Product__c WHERE Account__c = :accountId AND (Direct_Enabled__c = TRUE OR Local_Enabled__c = TRUE ))
                    AND (NACA_Case_Qty__c != null OR EMEA_Case_Qty__c != null))
            LIMIT :MAX_RESULTS
        ];
    
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        Product2[] products = (List<Product2>) searchResults[0];
        for (Product2 product : products) {
            String subtitle = 'Product';
            subtitle += product.ProductCode == null ? ' • SKU: N/A' : ' • SKU: ' + product.ProductCode;
            subtitle += product.NACA_Case_Qty__c != null ? ' • UoM: ' + product.NACA_Case_Qty__c : ' • UoM: ' + product.EMEA_Case_Qty__c;
            results.add(new LookupSearchResult(product.Id, 'Product2', PRODUCT2_ICON, product.Name, subtitle));
        }
        
        results.sort();
        return results;
    }

    @AuraEnabled
    public static List<LookupSearchResult> searchProducts(String searchTerm, List<String> selectedIds) {
        List<List<SObject>> searchResults = [
            FIND :searchTerm
            IN ALL FIELDS
            RETURNING
                Product2(Id, Name, ProductCode, NACA_Case_Qty__c, EMEA_Case_Qty__c, SAP_Code__c WHERE Id NOT IN :selectedIds 
                    AND (NACA_Case_Qty__c != null OR EMEA_Case_Qty__c != null))
            LIMIT :MAX_RESULTS
        ];
    
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        Product2[] products = (List<Product2>) searchResults[0];
        for (Product2 product : products) {
            String subtitle = 'Product';
            subtitle += product.ProductCode == null ? ' • SKU: N/A' : ' • SKU: ' + product.ProductCode;
            subtitle += product.NACA_Case_Qty__c != null ? ' • UoM: ' + product.NACA_Case_Qty__c : ' • UoM: ' + product.EMEA_Case_Qty__c;
            results.add(new LookupSearchResult(product.Id, 'Product2', PRODUCT2_ICON, product.Name, subtitle));
        }
        
        results.sort();
        return results;
    }
}