force-app/main/default/objects/SAP_Setting__mdt/SAP_Setting__mdt.object-meta.xml
<CustomObject>
    <label>SAP Setting</label>
    <pluralLabel>SAP Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAP_Setting__mdt/fields/Skipped_Account_by_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Skipped_Account_by_Ownership__c</fullName>
    <inlineHelpText>List of Owner for whom Accounts should not be transferred to Salesforce. Separated by semicolon.</inlineHelpText>
    <label>Skipped Account by Ownership</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAPSettingHelper.cls
public with sharing class SAPSettingHelper {
	public static Set<String> buildSalesOwnersToSkipSet(SAP_Setting__mdt sapSetting) {
		Set<String> skipSet = new Set<String>();

		if(sapSetting == null || sapSetting.Skipped_Account_by_Ownership__c == null){
			return skipSet;
		}

		for(String temp : (sapSetting.Skipped_Account_by_Ownership__c).split(';')){
			skipSet.add(temp);
		}

		return skipSet;
	}
}