force-app/main/default/objects/Opportunity/fields/Business_Partner__c.field-meta.xml
<CustomField>
    <fullName>Business_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Partner is the entity somehow involved with the opportunity. Not all opportunities need to have a Partner involved.</inlineHelpText>
    <label>Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>notEqual</operation>
            <valueField>Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Lost_LOTs__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_LOTs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closed Lost LOTs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Closed_Won_LOTs__c.field-meta.xml
<CustomField>
    <fullName>Closed_Won_LOTs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closed Won LOTs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Disqualified_LOTs__c.field-meta.xml
<CustomField>
    <fullName>Disqualified_LOTs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Disqualified LOTs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Revenue_on_LOTs__c.field-meta.xml
<CustomField>
    <fullName>Expected_Revenue_on_LOTs__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Summarized Expected Revenue from each LOT.</inlineHelpText>
    <label>Expected Revenue on LOTs</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_LOTs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_LOTs__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Overall number of LOTs</inlineHelpText>
    <label>Number of LOTs</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Open_LOTs__c.field-meta.xml
<CustomField>
    <fullName>Open_LOTs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Open LOTs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTenderLotRollupHelperTest.cls
@isTest
public class OpportunityTenderLotRollupHelperTest {

    private static final string TENDER_NAME = 'TEST-EMEA-Tender';

    @TestSetup
    static void makeData(){
        Account acc = new TestHelper.AccountRecord()
            .asEMEA()
            .save();

        Pricebook2 customPricebook = new TestHelper.PricebookRecord().save();

        Opportunity opp = new TestHelper.OpportunityRecord (
            TENDER_NAME, acc.Id, Constants.opportunity.RECORD_TYPE_EMEA_TENDER_ID )
            .setPricebookId(customPricebook.Id)
            .setStage(Constants.opportunity.STAGE_ANALYZING)
            .setCurrencyIsoCode('EUR')
            .save();

        Opportunity openLOT = new TestHelper.OpportunityRecord (
            'TEST-open-LOT', acc.Id, Constants.opportunity.RECORD_TYPE_EMEA_TENDER_LOT_ID)
            .setParent(opp.Id)
            .setAmount(1000)
            .setStage(Constants.opportunity.STAGE_ANALYZING)
            .setPricebookId(customPricebook.Id)
            .setCurrencyIsoCode('EUR')
            .build();

        Opportunity closedWonLOT = new TestHelper.OpportunityRecord (
            'TEST-closed-won-LOT', acc.Id, Constants.opportunity.RECORD_TYPE_EMEA_TENDER_LOT_ID)
            .setParent(opp.Id)
            .setAmount(1000)
            .setStage(Constants.opportunity.STAGE_CLOSED_WON)
            .setPricebookId(customPricebook.Id)
            .setCurrencyIsoCode('EUR')
            .build();

        insert new List<Opportunity>{openLOT, closedWonLOT};
    }

    @isTest
    private static void LOT_CreatedTest(){
        Opportunity tender = getTender();

        Test.startTest();
            new TestHelper.OpportunityRecord (
                'TEST-open-LOT', tender.AccountId, Constants.opportunity.RECORD_TYPE_EMEA_TENDER_LOT_ID)
                .setParent(tender.Id)
                .setAmount(1000)
                .setStage(Constants.opportunity.STAGE_ANALYZING)
                .setPricebookId(tender.Pricebook2Id)
                .setCurrencyIsoCode(tender.CurrencyIsoCode)
                .save();
        Test.stopTest();

        tender = getTender();

        System.assertEquals(3, tender.Number_of_LOTs__c);
        System.assertEquals(1, tender.Closed_Won_LOTs__c);
        System.assertEquals(2, tender.Open_LOTs__c);
        System.assertEquals(1200, tender.Expected_Revenue_on_LOTs__c);

    }

    @isTest
    private static void LOT_UpdatedTest(){
        Opportunity tender = getTender();

        Opportunity openLOT = tender.Opportunities__r[0];
        openLOT.Amount = 2000;

        Test.startTest();
            update openLOT;
        Test.stopTest();

        tender = getTender();

        System.assertEquals(2, tender.Number_of_LOTs__c);
        System.assertEquals(1, tender.Closed_Won_LOTs__c);
        System.assertEquals(1, tender.Open_LOTs__c);
        System.assertEquals(1200, tender.Expected_Revenue_on_LOTs__c);
    }

    @isTest
    private static void LOT_DeletedTest(){
        Opportunity tender = getTender();

        Test.startTest();
            delete tender.Opportunities__r[0];
        Test.stopTest();

        tender = getTender();

        System.assertEquals(1, tender.Number_of_LOTs__c);
        System.assertEquals(1, tender.Closed_Won_LOTs__c);
        System.assertEquals(0, tender.Open_LOTs__c);
        System.assertEquals(1000, tender.Expected_Revenue_on_LOTs__c);
    }

    @isTest
    private static void ALL_LOTs_DeletedTest(){
        Opportunity tender = getTender();

        Test.startTest();
            delete tender.Opportunities__r;
        Test.stopTest();

        tender = getTender();

        System.assertEquals(0, tender.Number_of_LOTs__c);
        System.assertEquals(0, tender.Closed_Won_LOTs__c);
        System.assertEquals(0, tender.Open_LOTs__c);
        System.assertEquals(0, tender.Expected_Revenue_on_LOTs__c);
    }

    private static Opportunity getTender(){
        return [
            SELECT Id, AccountId, Pricebook2Id, CurrencyIsoCode,
                Number_of_LOTs__c, Open_LOTs__c, Closed_Lost_LOTs__c, Closed_Won_LOTs__c, Disqualified_LOTs__c, Expected_Revenue_on_LOTs__c,
                (SELECT Id, Amount FROM Opportunities__r ORDER BY Probability)
            FROM Opportunity 
            WHERE Name = :TENDER_NAME 
            LIMIT 1
        ];
    }
}