force-app/main/default/objects/Opportunity/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
                <default>true</default>
                <label>Yearly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Target_Convert_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Convert_Date__c</fullName>
    <inlineHelpText>The Target Convert date is when we can expect to see the revenue come in.</inlineHelpText>
    <label>Target Convert Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateOpportunityScheduleTest.cls
@isTest
public class CreateOpportunityScheduleTest {
	@isTest
    public static void createSch(){
        OpportunityLineItem oppLineItem = new TestHelper.OpportunityLineItemRecord().setSalesPrice(10).save();
        Opportunity opp = [Select Id from Opportunity limit 1];
        opp.Target_convert_date__c = date.today().addMonths(12);
        opp.Frequency__c = 'Monthly';
        update opp;
        Test.startTest();
        ScheduleClassForRevenueCalculation sh1 = new ScheduleClassForRevenueCalculation();
        String sch = '0 0 2 * * ?'; 
        system.schedule('ScheduleClassForRevenueCalculation', sch, sh1); 
        Test.stopTest();
    }
    
    @isTest
    public static void createSchYrly(){
        OpportunityLineItem oppLineItem = new TestHelper.OpportunityLineItemRecord().setSalesPrice(10).save();
        Opportunity opp = [Select Id from Opportunity limit 1];
        opp.Target_convert_date__c = date.today().addMonths(12);
        opp.Frequency__c = 'Yearly';
        update opp;
        Test.startTest();
        ScheduleClassForRevenueCalculation sh1 = new ScheduleClassForRevenueCalculation();
        String sch = '0 0 2 * * ?'; 
        system.schedule('ScheduleClassForRevenueCalculation', sch, sh1); 
        Test.stopTest();
    }
}