force-app/main/default/objects/Quote_Line_Item_History__c/Quote_Line_Item_History__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item History</label>
    <nameField>
        <label>Quote Line Item History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Items History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item_History__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quote Line Items History</relationshipLabel>
    <relationshipName>Quote_Line_Items_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item_History__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items History</relationshipLabel>
    <relationshipName>Quote_Line_Items_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>17</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemTriggerHandler.cls
public with sharing class QuoteLineItemTriggerHandler {
	private static List<QuoteLineItem> filterQlisForQliHistorySnapshot (Map<Id, QuoteLineItem> oldQlisById, Map<Id, QuoteLineItem> newQlisById) {
		List<QuoteLineItem> filteredQlis = new List<QuoteLineItem>();
		for(QuoteLineItem oldQli : oldQlisById.values()) {
			QuoteLineItem newQli = newQlisById.get(oldQli.Id);
			if(oldQli.UnitPrice != newQli.UnitPrice
				|| oldQli.TotalPrice != newQli.TotalPrice
				|| oldQli.Quantity != newQli.Quantity) {
				filteredQlis.add(oldQli);
			}
		}
		return filteredQlis;
	}

	public static void createQlisHistory (Map<Id, QuoteLineItem> oldQlisById, Map<Id, QuoteLineItem> newQlisById) {
		List<QuoteLineItem> filteredQlis = filterQlisForQliHistorySnapshot(oldQlisById, newQlisById);
		List<Quote_Line_Item_History__c> qlisHistory = new List<Quote_Line_Item_History__c>();

		for(QuoteLineItem qli : filteredQlis) {
			qlisHistory.add(
				new Quote_Line_Item_History__c(
					Quote__c = qli.QuoteId,
					Quote_Line_Item__c = qli.Id,
					Sales_Price__c = qli.UnitPrice,
					Quantity__c = qli.Quantity,
					Total_Price__c = qli.TotalPrice
				)
			);
		}
		insert qlisHistory;
	}
}